# Generated by Django 5.0 on 2023-12-23 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_comment_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='body',
        ),
    ]
