# Generated by Django 5.0 on 2024-02-24 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_reply_delete_subcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='articles.comment'),
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
